project:
  type: website

website:
  title: "Transparencia"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - sobre.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



